name: myapp
description: "Application mobile e-commerce Ishrili Mauritanie."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  # UI & Icons
  cupertino_icons: ^1.0.8

  # State Management
  provider: ^6.1.5
  
  # HTTP & API Calls
  http: ^1.4.0
  dio: ^5.3.2
  
  # Local Storage
  shared_preferences: ^2.5.3
  
  # Navigation
  go_router: ^15.1.3
  
  # Image Handling
  cached_network_image: ^3.4.1
  image_picker: ^1.1.2
  
  # Utils
  intl: ^0.20.2
  uuid: ^4.5.1
  
  # Authentication (optionnel pour plus tard)
  # google_sign_in: ^6.2.1
  
  # Notifications (optionnel pour plus tard)
  # flutter_local_notifications: ^16.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Assets pour votre app (logos, images, etc.)
  assets:
    - assets/images/
    - assets/icons/
  
  # Polices personnalisées si nécessaire
  # fonts:
  #   - family: Poppins
  #     fonts:
  #       - asset: assets/fonts/Poppins-Regular.ttf
  #       - asset: assets/fonts/Poppins-Bold.ttf
  #         weight: 700
  